import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Barlow } from "next/font/google";
import "./globals.css";

import { createSupabaseServer } from "@/lib/supabase-server";


const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServer();
  const { data: { user } } = await supabase.auth.getUser();
  return (
    <html lang="en">
  
      <body className={`${geistSans.variable} ${geistMono.variable} ${barlow.className} min-h-screen flex flex-col`}>
        <main className="flex-1 pt-[10vh]">
          {children}
        </main>
       
      </body>
    </html>
  );
}
